### ISSUE TITLE
Error handling: Fix the empty query error handling.

### ISSUE THREAD

**Issue by suhaskv1** [acmpesuecc/NoSpoilers#2]
## Description
In the tk_gui.py, line 29; the exception is seemingly crashing the program when the input query is empty. Look for a better way to implement the same functionality with better error handling. 

## Bug Replication
1) Run the tk_gui.py file.
2) Do not enter any query into the entry and press enter to replicate this bug.

Things to note
- Comments are required for this task.
- Follow the same coding style.

## Resources
Refer to this [link](https://docs.python.org/3/tutorial/errors.html) to learn more about error handling.

**Bounty points allotted: 30+**

Please feel free to contact the maintainers in case of any issues or queries. Happy contributing!

**Comment by suhaskv1** [comment]
Sure! Good luck!

**Comment by charan2308** [comment]
Hey, I want to work on this.

**Comment by prishagoel** [comment]
Hi, can you assign this to me?
