### ISSUE TITLE
Bug: Adding show(s)  with commas in its name breaks program on Next open

### ISSUE THREAD

**Issue by Smuzzy-waiii** [acmpesuecc/NoSpoilers#24]
Adding a show like "Go, Diego, Go!" which has commas in its title throws
```Exception: Row has incorrect number of values``` from the ```load_watchlist()``` function the next time you try to open it since
```
def load_watchlist():
        '''
        This function is to load the saved watchlist everytime the application is opened
        '''
        file = open('wlist.txt', 'r')
        for x in file:
                a = x.split(', ')
                print(a)
                mytable.add_row(a)
```
since list a is now longer than expected by ```mytable.add_row(a)```

**Comment by Smuzzy-waiii** [comment]
May I be assigned to this

**Comment by prishagoel** [comment]
Hi, I would like to work on this?

**Comment by suhaskv1** [comment]
You have been assigned! Good luck!
